create table if not exists public.registrations (
    id bigint generated by default as identity primary key,
    name text not null,
    student_id text not null unique,
    created_at timestamptz not null default now(),
    constraint registrations_name_length check (char_length(name) >= 2),
    constraint registrations_student_id_length check (char_length(student_id) between 6 and 20)
);

create index if not exists registrations_created_at_idx
on public.registrations (created_at desc);

alter table public.registrations enable row level security;

revoke all on table public.registrations from anon, authenticated;
